" Use Vim settings, rather than Vi settings
" Must be first!
set nocompatible

" Enable file type detection and do language-dependent indenting
filetype plugin indent on

" Make backspace behave in a sane manner
set backspace=indent,eol,start

" Turn on syntax highlighting
syntax on

" Show whitespace characters
set list
set listchars=tab:→\ ,space:·
highlight SpecialKey ctermfg=grey guifg=grey70

" Enable file type detection and do language-dependent indenting
filetype plugin indent on

" Show line numbers
set nu

""" Vim-Plug
"
" Specify directory for plugins
call plug#begin('~/.vim/plugged')

" Syntastic
Plug 'vim-syntastic/syntastic'

" Typescript syntax highlighting
Plug 'leafgarland/typescript-vim'

" Typescript IDE
Plug 'Shougo/vimproc.vim', {'do' : 'make'}
Plug 'Quramy/tsuquyomi'

" Initialize plugin system
call plug#end()

""" Syntastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

""" Tsuquyomi
let g:tsuquyomi_disable_quickfix = 1

