" Use Vim settings, rather than Vi settings
" Must be first!
set nocompatible

" Make backspace behave in a sane manner
set backspace=indent,eol,start

" Turn on syntax highlighting
syntax on

" Enable file type detection and do language-dependent indenting
filetype plugin indent on

" Show line numbers
set nu

"" Vim-Plug
"
" Specify directory for plugins
call plug#begin('~/.vim/plugged')

" Typescript syntax highlighting
Plug 'leafgarland/typescript-vim'

" Typescript IDE
Plug 'Shougo/vimproc.vim', {'do' : 'make'}
Plug 'Quramy/tsuquyomi'

" Python stuff
Plug 'ambv/black'


" Initialize plugin system
call plug#end()
