" Use Vim settings, rather than Vi settings
" Must be first!
set nocompatible

map <Space> <Leader>

" Enable file type detection and do language-dependent indenting
filetype plugin indent on

" Make backspace behave in a sane manner
set backspace=indent,eol,start

" Turn on syntax highlighting
syntax on

" Show whitespace characters
set list
set listchars=tab:→\ ,space:·
highlight SpecialKey ctermfg=grey guifg=grey70

" Show incremental searches
set incsearch

" Highlight all search matches
set hlsearch

" Enable file type detection and do language-dependent indenting
filetype plugin indent on

" Show line numbers
set number
set relativenumber

" Source vimrc with leader cl (config load)
nnoremap <leader>co :edit $MYVIMRC<cr>
nnoremap <leader>cl :source $MYVIMRC<cr>

""" Vim-Plug
"
" Specify directory for plugins
call plug#begin('~/.vim/plugged')

" Plugin for automatically setting indentation settings
Plug 'tpope/vim-sleuth'

" File opener
Plug 'kien/ctrlp.vim'

" Exclude gitignored files from ctrlp
let g:ctrlp_user_command = ['.git/', 'git --git-dir=%s/.git ls-files -oc --exclude-standard']

" Bind ctrlp to leader P
nnoremap <leader>p  :CtrlP .<cr>

" Syntastic
Plug 'vim-syntastic/syntastic'

" Typescript syntax highlighting
Plug 'leafgarland/typescript-vim'

" Initialize plugin system
call plug#end()

